### ISSUE TITLE
can't compose and pull 

### ISSUE THREAD

**Issue by qq8554650** [stdevPavelmc/openvpn-as#1]
![openvpn-as](https://user-images.githubusercontent.com/22789241/212472544-07f989e7-be68-4c27-89aa-4080bb33de6c.png)

**Comment by stdevPavelmc** [comment]
This repo is archived and not maintained and the image was removed.

Sorry, this was a personal image and it won't turned well, so I archived it, sorry for the inconvenience.

But, nothing stop you to fork it and fix/improve for you.

Cheers
